global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'personalized-assistant-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'personalized-assistant-auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'personalized-assistant-data-collection-service'
    static_configs:
      - targets: ['data-collection-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'personalized-assistant-data-processing-service'
    static_configs:
      - targets: ['data-processing-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'personalized-assistant-chat-agent-service'
    static_configs:
      - targets: ['chat-agent-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

